# -*- coding: utf-8 -*-
"""Minor Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L5ETkKHBzWiwHRNu416TZ21w7KvxzXSS

Minor project submission : HONEY PRODUCTION
* Name : Megha Arora
* Enrollment number : 10501172021
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('seaborn')

df = pd.read_csv('/content/honeyproduction.csv')

df.head()

"""Q1 Explore quantitative variables and qualitative variables in the dataset"""

df.info()

"""* There are 7 quantitave and 1 qualitative variable in the given data set
* The set of quantitative variables include number of colonies (numcol), yield per colony (yieldpercol), total production (totalprod), stocks, price per lb (priceperlb), production value (prodvalue) and year
* State is a qualitative variable
* The above table shows that there are 626 entries indexing from 0 to 625
* It shows that there are 8 columns, the number of not null values and the corresponding datatype

Q2 Find the relationship between numerical variables using pair plots and correlational plots. Explain what you infer from there plots
"""

a = sns.pairplot(df1)

"""PAIRPLOT"""

a = sns.heatmap(df.corr(),annot=True)

"""CORRELATIONAL PLOT
* In the above heat map, we have three kinds of values
* If the relationship value is 1, it represents the same quantity
* If the relationship value is greater than 0.5 or 0.6, the two quantities are directly proportional 
* The one's approaching zero do not have any significant relationship

Q3 Look at the overall trend of honey production in the US over the years
"""

x = df['year']
y = df['totalprod']
plt.bar(x,y)
plt.xlabel('YEAR')
plt.ylabel('TOTAL PRODUCTION')
plt.title('BAR CHART OF TOTAL PRODUCTION V/S YEAR')
plt.plot()

"""* Total honey production was minimum in the year 2002
* Total honey production was maximum in the year 2010

Q4 Are there any patterns that can be observed between total honey production, which in some sense could be tied to demand, changed every year
"""

x = df['totalprod']
y = df['prodvalue']
plt.scatter(x,y)
plt.xlabel('TOTAL PRODUCTION')
plt.ylabel('PRODUCTION VALUE')
plt.title('SCATTER PLOT OF TOTAL PRODUCTION V/S PRODUCTION VALUE')
plt.show()

"""From the above plot, we can conclude that as the total production increases, the value of production also increases

Q5 Observe the variation in the number of colonies over the years
"""

x = df['year']
y = df['numcol']
plt.bar(x,y)
plt.xlabel('YEAR')
plt.ylabel('NUMBER OF COLONIES')
plt.title('BAR CHART OF YEAR V/S NUMBER OF COLONIES')
plt.show()

"""* Number of colonies remains between 400000 and 500000 over the years
* In the year 2006, there are least number of colonies
* In the year 2010, there are maximum number of colonies

Q6 Analyze the variation of yeild per colony over the years and the production trend at state level and brief out what yu observed
"""

x = df['year']
y = df['yieldpercol']
plt.bar(x,y)
plt.xlabel('YEAR')
plt.ylabel('YIELD PER COLONY')
plt.title('BAR CHART OF YEAR V/S YIELD PER COLONY')
plt.show()

"""* The above chart shows that yeild per colony has decreased over the years 
* The yeild was minimum in the year 2007
* The yeild was maximum in the year 2002
"""

x = df['state']
y = df['prodvalue']
plt.bar(x,y)
plt.xlabel('STATE')
plt.ylabel('PRODUCTION VALUE')
plt.title('BAR CHART OF PRODUCTION VALUE V/S STATE')
plt.show()

df[df['prodvalue'] == max(df['prodvalue'])]

df[df['prodvalue'] == min(df['prodvalue'])]

"""* Production value of state ND is greater than the rest
* Production value of state MD is the least

Q7 Analyse what effect the declining production trend has had on the value of production
"""

a = np.array(df['totalprod'])
b = np.array(df['year'])
plt.plot(b,a,'bo')
plt.xlabel('YEAR')
plt.ylabel('TOTAL PRODUCTION')
plt.title('PLOT OF YEAR V/S TOTAL PRODUCTION')
plt.show()

"""* Due to the declining production trend, the total production is decreasing
* Hence, the value of production is also decreasing
"""